syntax on
set nocindent
set smartindent
set tabstop=8
set shiftwidth=4
set expandtab
set viminfo='20,\"5000
set history=5000
set hlsearch
set novisualbell
set background=dark
set backspace=eol,indent,start
set nowrap
set number
